steps:
  # Build the Flutter web app
  - name: 'ghcr.io/cirruslabs/flutter:stable'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        flutter pub get
        flutter build web --release

  # Build Docker image (using production Dockerfile)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/azam-pos-report:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/azam-pos-report:latest'
      - '-f'
      - 'Dockerfile.prod'
      - '.'

  # Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/azam-pos-report:$BUILD_ID'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/azam-pos-report:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'azam-pos-report'
      - '--image'
      - 'gcr.io/$PROJECT_ID/azam-pos-report:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'

images:
  - 'gcr.io/$PROJECT_ID/azam-pos-report:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/azam-pos-report:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
